/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as JogoImport } from './routes/jogo'
import { Route as CameraImport } from './routes/camera'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const JogoRoute = JogoImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => rootRoute,
} as any)

const CameraRoute = CameraImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraImport
      parentRoute: typeof rootRoute
    }
    '/jogo': {
      id: '/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof JogoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/jogo': typeof JogoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/jogo': typeof JogoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/jogo': typeof JogoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/camera' | '/jogo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/camera' | '/jogo'
  id: '__root__' | '/' | '/camera' | '/jogo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  JogoRoute: typeof JogoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  JogoRoute: JogoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/camera",
        "/jogo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/camera": {
      "filePath": "camera.tsx"
    },
    "/jogo": {
      "filePath": "jogo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
